# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Default values for zipkin.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.

# https://helm.sh/docs/chart_best_practices/values

# -- Namespace in NOTES.txt
namespace: acme

# -- Defaultwert ist im Chart bei `name` und kann überschrieben werden.
nameOverride: ""

# -- _Fully Qualified Name (FQN)_ ist defaultmäßig im Chart bei `name` und kann überschrieben werden.
fullnameOverride: ""

# -- Anzahl Replica im Pod von Kubernetes
replicaCount: 1

image:
  # -- Repository als Präfix beim Image-Namen
  repository: openzipkin
  # -- Name des Image
  name: zipkin
  # -- Pull-Policy für das Image
  pullPolicy: IfNotPresent
  # -- Defaultwert ist im Chart bei `appVersion` und kann überschrieben werden.
  tag: ""

resourcesRequests:
  # -- (Mindest-) Anforderung an CPU-Ressourcen in _millicores_, z.B. `500m` oder `1`
  cpu: 500m
  # -- (Mindest-) Anforderung an Memory-Resourcen als _mebibyte_ Wert
  memory: 512Mi
  # -- (Mindest-) Anforderung an flüchtigen Speicher für z.B. Caching und Logs
  ephemeral: 64Mi

resourcesLimits:
  # -- Maximalanforderung an CPU-Ressourcen in _millicores_, z.B. `500m` oder `1`
  cpu: 500m
  # -- Maximalanforderung an Memory-Resourcen als _mebibyte_ Wert
  memory: 512Mi
  # -- Maximalanforderung an flüchtigen Speicher für z.B. Caching und Logs
  ephemeral: 64Mi

autoscaling:
  # -- Ist Autoscaling aktiviert?
  enabled: true
  # -- Mininmale Anzahl an Replicas
  minReplicas: 1
  # -- Maximale Anzahl an Replicas
  maxReplicas: 2
  # -- Maximale CPU-Auslastung
  targetCPUUtilizationPercentage: 80
  # -- Maximale RAM-Auslastung
  targetMemoryUtilizationPercentage: 80
