# Copyright (C) 2023 - present Juergen Zimmermann, Hochschule Karlsruhe
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <https://www.gnu.org/licenses/>.

# Aufruf:   docker compose up
#               http://localhost:9411/zipkin
#           docker compose down

services:
  zipkin:
    # Image basierend auf nginx als Webserver
    image: openzipkin/zipkin:2.24.4
    ports:
      - published: 9411
        target: 9411
    restart: always
    container_name: zipkin
    #extra_hosts: ['host.docker.internal']
