@startuml ER Diagramm

' hide the spot
hide circle

' evtl. Prbleme mit Kraehenfuessen vermeiden
skinparam linetype ortho

entity "Trainer" {
  * id : UUID <<generated>>
  --
  * vorname : text
  * nachname : text
}

entity "Mannschaft" {
  * id : UUID <<generated>>
  --
  * version: integer
  * name : text
  * gruendungsjahr: date
  * **trainer_id**: UUID <<FK>>
    username: text
  * erzeugt: timestamp
  * aktualisiert: timestamp
}

entity "Spieler" {
  * id : UUID <<generated>>
  --
  * vorname : text
  * nachname : text
  * **mannschaft_id**: UUID <<FK>>
}

Mannschaft ||.left.|| Trainer
Mannschaft ||.right.o{ Spieler

footer (c) Jürgen Zimmermann

@enduml
