@startuml Komponenten

package com.acme.mannschaft #DDDDDD {
    package rest <<boundary>> #FFFFFF {
        [@RestController\nMannschaftGetController] as MannschaftGetController
        [@RestController\nMannschaftWriteController] as MannschaftWriteController
    }

    package service <<control>> #FFFFFF {
        [@Service\nMannschaftReadService] as MannschaftReadService
        [@Service\nMannschaftWriteService] as MannschaftWriteService
    }

    package repository <<control>> #FFFFFF {
        [MannschaftRepository]
    }

    package entity <<entity>> #FFFFFF {
        [Mannschaft]
    }
}

cloud {
    [Spring Data]
}

database "mannschaft (PostgreSQL)" {
    [Tabelle mannschaft]
    [Tabelle spieler]
    [Tabelle trainer]

    [Tabelle mannschaft] -[hidden]-> [Tabelle trainer]
    [Tabelle trainer] -[hidden]-> [Tabelle spieler]
}

RESTClient ~~> [MannschaftGetController]
RESTClient ~~> [MannschaftWriteController]

[MannschaftGetController] --> [MannschaftReadService]
[MannschaftWriteController] --> [MannschaftWriteService]
[MannschaftReadService] --> [MannschaftRepository]
[MannschaftWriteService] --> [MannschaftRepository]

[MannschaftGetController] .left.> [Mannschaft]
[MannschaftWriteController] ..> [Mannschaft]
[MannschaftReadService] .left.> [Mannschaft]
[MannschaftWriteService] ..> [Mannschaft]
[MannschaftRepository] ..> [Mannschaft]

[MannschaftRepository] ~right~> [Spring Data]
[Spring Data] ~right~> [Tabelle mannschaft]
[Spring Data] ~~> [Tabelle trainer]
[Spring Data] ~~> [Tabelle spieler]

footer (c) Jürgen Zimmermann

@enduml
